FROM openjdk:8-jre-slim
  
# Add the jar with all the dependencies
# Maven creates container-test.jar in the target folder of my workspace.
# We need this in some location - say - /usr/share/tag folder of the container
ADD  target/project.jar /usr/share/tag/project.jar

# Command line to execute the test
ENTRYPOINT ["/usr/bin/java", "-cp", "/usr/share/tag/projectearf.jar", "org.testng.TestNG", "-testclass", "com.converge.projectEARF.AppTest"]